### ISSUE TITLE
Question: Serializer of hunter.Event. Maybe to JSON?

### ISSUE THREAD

**Issue by guettli** [ionelmc/python-hunter#102]
@ionelmc Hi,

I would like to serialize hunter.Event to JSON. And later create HTML from the JSON.

Before I waste too much time re-inventing this, I would like to ask: Is there already a 
serializer you know?

thank you for this great library!

**Comment by ionelmc** [comment]
Well currently there's no support but there's some discussion: https://github.com/ionelmc/python-hunter/issues/74

It's possible to implement now I believe, it's just a matter of figuring the equivalent for the `__reduce__`/`__settate__` in the Cython implementation and implementing said boilerplate for Events. I mean it's just the events to serialize (which are pretty flat) so it's not a huge amount of work.

For json I believe you could call `__reduce__` directly to generate whatever you want. Or use https://github.com/jsonpickle/jsonpickle I guess...

**Comment by guettli** [comment]
thank you for the quick answer. Dumping the event to JSON is simple. If I have something worth sharing, I will contact you again.
