### ISSUE TITLE
Have a builtin filter that just excludes all the stdlib modules

### ISSUE THREAD

**Issue by ionelmc** [ionelmc/python-hunter#15]
Something like `hunter.trace(builtins=False)` or `Q(builtins=False)`

**Comment by The-Compiler** [comment]
FWIW, +1 from me :wink:

**Comment by ionelmc** [comment]
FYI, just added this in master (`stdlib` instead of `builtins`)

**Comment by ionelmc** [comment]
Released in `0.6.0`.
