### ISSUE TITLE
Tracing cython code

### ISSUE THREAD

**Issue by licnep** [ionelmc/python-hunter#30]
hunter.trace() fails to print the source code for cython modules, even when they are cythonized with linetracing enabled (eg. when an exception happens the source code is shown).

Instead of showing the pyx source, hunter currently outputs lines like this:

`cythonLib.so:275   line      ??? NO SOURCE: SyntaxError("invalid or missing encoding declaration for '/usr/local/lib/python3.5/dist-packages/cythonLib.so'")`

**Comment by ionelmc** [comment]
This is supported now. Note that you need to enable line tracing (see `tests/sample5.pyx` and `tests/setup.py` for what I tested with).

**Comment by licnep** [comment]
Awesome!
