### ISSUE TITLE
ImportError: No module named manhole

### ISSUE THREAD

**Issue by guettli** [ionelmc/python-hunter#47]
I installed hunter via pip.

Now I get this:

```
Traceback (most recent call last):
  File "/home/myvenv/bin/hunter-trace", line 7, in <module>
    from hunter.remote import main
  File "/home/myvenv/lib/python2.7/site-packages/hunter/remote.py", line 15, in <module>
    import manhole
ImportError: No module named manhole


```

After installing manhole it works.

Maybe add it to `install_requires` of setup.py?

**Comment by ionelmc** [comment]
It's in the extras, is `pip install hunter[remote]` not mentioned anywhere? Hmmm.

**Comment by guettli** [comment]
one question remains:

Why not install manhole always (unconditionally)?

**Comment by ionelmc** [comment]
Manhole doesn't work on Windows (uses unix domain sockets).
