### ISSUE TITLE
Docs: module_sw I need to guess

### ISSUE THREAD

**Issue by guettli** [ionelmc/python-hunter#50]
Here you use "module_sw": https://python-hunter.readthedocs.io/en/latest/readme.html?highlight=module_sw

I know that I am a bit autistic..... I need to guess that "module_sw" means "startwith".

Here module_sw does not get used: https://python-hunter.readthedocs.io/en/latest/introduction.html

For obtrusive people like me it would be easier to have exactly one way to write this :-)

**Comment by ionelmc** [comment]
Yes but convenience is also important. I'll fix the docs.

**Comment by guettli** [comment]
@ionelmc I see you are talented and you care for docs. I guess you will be successful. I wish you good luck!  Do not forget there is live outside the internet (friends, family) :-)

**Comment by ionelmc** [comment]
Thanks :)))
