### ISSUE TITLE
`hunter.Event` documentation is missing available fields in latest docs

### ISSUE THREAD

**Issue by chrahunt** [ionelmc/python-hunter#55]
In the latest version of the documentation `hunter.Event` is pretty bare, only showing the class description, but no attributes. See [here](https://python-hunter.readthedocs.io/en/latest/reference.html#hunter.Event). This only impacts latest - both stable and 2.2.1 look good and have all the relevant fields.

**Comment by ionelmc** [comment]
Uh ... does it now have all the stuff?

**Comment by chrahunt** [comment]
Still happening for me. Compare stable:

![Reference — Hunter 2 2 1 documentation - Mozilla Firefox_006](https://user-images.githubusercontent.com/2312275/59147802-247dc000-89ce-11e9-838d-4d94b8c80db1.png)

vs latest:

![Reference — Hunter 0 1 dev53 documentation - Mozilla Firefox_007](https://user-images.githubusercontent.com/2312275/59147812-38c1bd00-89ce-11e9-826a-6559988b8d41.png)

**Comment by ionelmc** [comment]
Ooof ... now it should be fixed for real.
