### ISSUE TITLE
How to avoid object memory reference in output?

### ISSUE THREAD

**Issue by guettli** [ionelmc/python-hunter#58]
I have bug which only appears on one system, not on other systems.

I want to trace a script and compare the output.

I run it once in the buggy environment, and once in the working environment.

There are two times 40k lines output. I use a diff-tool (meld) to compare both traces.

It works ... mostly.

Unfortunately there a lot of lines like this: `__init__(self=<foolib.FooClass object at 0x7fc6dc14b600>)`

The diff tool marks these lines as different.

How to make hunter stop printing the memory address (` 0x7fc6dc14b600`)?

It would be very nice if this would be solveable without changing the code. I use the `PYTHONHUNTER` environment variable to enable tracing.

**Comment by ionelmc** [comment]
Well if you need something right now then either (monkey)patch rudimentary_repr in utils.py or sed the address out of the output.

I'll consider allowing users using their own repr functions in a future version.

**Comment by guettli** [comment]
> I'll consider allowing users using their own repr functions in a future version.

This would be great.

**Comment by guettli** [comment]
thank you very much for added this.

**Comment by ionelmc** [comment]
Hunter 3.0 is released.
