### ISSUE TITLE
Hunter doesn't work when using py.io

### ISSUE THREAD

**Issue by chrahunt** [ionelmc/python-hunter#62]
When referencing `py.io.TerminalWriter` (probably other attributes as well), an exception is raised only when hunter is in use. Example:

```python
import py.io

py.io.TerminalWriter
```

```shell
test -d .venv || python3 -m venv .venv
. .venv/bin/activate
pip install py==1.8.0 hunter==2.2.1
echo '
import py.io

py.io.TerminalWriter
' > test.py
python test.py
```

No exception should appear.

When running with hunter, like

```shell
PYTHONHUNTER='stdlib=False, action=CallPrinter(stream=open("hunter.log", "w", encoding="utf-8"))' python test.py
```

the following exception occurs:

```
Traceback (most recent call last):
  File ".venv/lib/python3.7/site-packages/py/_vendored_packages/apipkg.py", line 141, in __makeattr
    modpath, attrname = self.__map__[name]
KeyError: 'TerminalWriter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    py.io.TerminalWriter
  File ".venv/lib/python3.7/site-packages/py/_vendored_packages/apipkg.py", line 146, in __makeattr
    raise AttributeError(name)
AttributeError: TerminalWriter
```

The exception does not occur if we omit `stdlib=False`.

The exception does not occur when excluding the `py._vendored_packages.apipkg`, like:

```shell
PYTHONHUNTER='Q(stdlib=False) & ~Q(module="py._vendored_packages.apipkg"), action=CallPrinter(stream=open("hunter.log", "w", encoding="utf-8"))' python test.py
```

Doing some debugging around the area in apipkg it looks like the act of introspecting happens at a time that causes the exception to be raised. Maybe the method is not re-entrant, but the printing would require it to be?

In case there's a fundamental issue that can't be solved, adding documentation to call this out as a limitation would be good.

Additionally, we could use some documentation on what to watch out for when debugging hunter-related issues. Even basic debugging (e.g. `breakpoint()`, pdb, intentionally raising exceptions, logging) gives confusing feedback - messages logged at the top of `__makeattr` are printed twice but unconditional exceptions only visibly raised once, same with breakpoints.

**Comment by ionelmc** [comment]
Oooooof .... apipkg does some shenanigans with `__dict__` of modules ... `hunter.util.rudimentary_repr` does a `hasattr(obj, '__dict__')` check 😞

**Comment by ionelmc** [comment]
A check like `'__dict__' not in getattr(obj_type, '__dict__', ()) and not hasattr(obj, '__dict__')` would fix it but then that would fail too if obj_type had a god damn descriptor as `__dict__` ...

**Comment by ionelmc** [comment]
So there's a fix in master, give it a try.

**Comment by chrahunt** [comment]
Looks good to me, feel free to close this issue.

**Comment by ionelmc** [comment]
Hunter 3.0 is released.
