### ISSUE TITLE
Jupyter Notebook - Trace missing code source

### ISSUE THREAD

**Issue by tigrus** [ionelmc/python-hunter#63]
We have following code: 

```
import hunter

hunter.trace(module=__name__, function='good_tracing_example', actions=[hunter.CallPrinter, hunter.VarsPrinter("a", "b", "result")])

class A(object): 
    def good_tracing_example(self, a, b):
        a += 3 
        a += 7
        a += 20
        result = a + b
        return result

class B(A):
    def good_tracing_example(self, a, b):
        b += 20
        a += 30 
        result = super().good_tracing_example(a, b)
        return result


b = B()
b.good_tracing_example(1, 2)
```

When we run it in jupyter cell - we have following result: 

![TracingNotebookCell](https://user-images.githubusercontent.com/804424/58189051-64e8f880-7cc2-11e9-926a-b18e115cd45f.PNG)

When we run it as bash command - we have much better result: 

![TracingBashCell](https://user-images.githubusercontent.com/804424/58189080-76ca9b80-7cc2-11e9-9588-2cb63d016d24.PNG)

How to make hunter work well in jupyter notebook?

**Comment by ionelmc** [comment]
Looks like hunter has made some bad assumptions about `__file__`. Will be fixed in next release.

**Comment by tigrus** [comment]
Thanks, looking forward for fix :)

**Comment by ionelmc** [comment]
Well feel free to try the master or wheel from a recent dev build: https://test.pypi.org/project/hunter/2.2.2.dev62/

**Comment by ionelmc** [comment]
Hunter 3.0 is released.
