### ISSUE TITLE
AttributeError: module 'hunter' has no attribute 'trace'

### ISSUE THREAD

**Issue by hbmartin** [ionelmc/python-hunter#76]
Getting this error on a fresh hunter install on mac with 3.7

**Comment by ionelmc** [comment]
Perhaps you have a `hunter.py` file in your working directory? What does the module contain? Try `dir(hunter)`, `hunter.__file__` etc

**Comment by hbmartin** [comment]
Derp, yes I named my script hunter, sorry and thanks!
