### ISSUE TITLE
PYTHONHUNTER="Q(module='os')"  is not working as expected in python2

### ISSUE THREAD

**Issue by ctrngk** [ionelmc/python-hunter#77]
Hi,

I evaluate legacy codes in python2 but it is not working as expected

demo.py is as follows
```python
import os
result = os.path.join("/etc", "networks")
print(result)
```
works in python3
```bash
PYTHONHUNTER="Q(module='os')" python3 demo.py
```

not in python2
```bash
PYTHONHUNTER="Q(module='os')" python2 demo.py
```

Regards,

**Comment by ionelmc** [comment]
I suspect you want to actually trace `os.path` instead yes? The problem is that `os.path` is aliased to ntpath or posixpath depending on platform at runtime (when you import `os`) so there's little that hunter can do for that, safely that is.

Would this solve the problem for you?
```
 PYTHONHUNTER='Q(module="os")|Q(module="ntpath")|Q(module="posixpath")' python...
```
