### ISSUE TITLE
List of all possible filters

### ISSUE THREAD

**Issue by abitrolly** [ionelmc/python-hunter#92]
There are no docs describing `filename_startswith` or `filename_contains` filters.

https://python-hunter.readthedocs.io/en/latest/configuration.html

This page mentions `filename_alignment` and doesn't include `filename`. It would be nice to see the list of all supported filter keywords to avoid guessing and hunting for examples. )

**Comment by ionelmc** [comment]
Any of the properties of Event: https://python-hunter.readthedocs.io/en/latest/reference.html#hunter.event.Event

I'm looking for a better way to enumerate them in the docs.

**Comment by abitrolly** [comment]
That's helpful. Thanks!
