### ISSUE TITLE
Is it possible to set the depth of tracing and store the execution time of called functions?

### ISSUE THREAD

**Issue by anki-code** [ionelmc/python-hunter#94]
Hi! Great tool! Many thanks!

I tried to use hunter to [dive into](https://github.com/xonsh/xonsh/issues/4125) the [xonsh shell](https://github.com/xonsh/xonsh/). The code is complex and I want to asking an advice.

Is there a way to restrict the depth and add time of execution for a functions/constructors? 

For example we have:
```python
def a():
    time.sleep(2)
    b = 1
c = 1
a()
```

In trace with depth=1 we have:

```python
c = 1
a() # 2 sec
```

In trace with depth=2 we have:

```python
c = 1
a()
    time.sleep(2)  # 2 sec
    b=1
# end a() - 2 sec
```

The depth could allow to go from whole to the details.

Is it possible?

Thanks!

PS: Meanwhile if you have another advice how to deep dive into the complex code with tracing please feel free to share!

**Comment by ionelmc** [comment]
You can add operators, eg: `depth_lt=5`, see https://python-hunter.readthedocs.io/en/latest/filtering.html

About durations (profiling basically) - it's kinda complicated, see https://python-hunter.readthedocs.io/en/latest/cookbook.html#profiling

**Comment by anki-code** [comment]
Many thanks for the fast answer! I will dive into this.

**Comment by anki-code** [comment]
Hi @ionelmc!
I tried:
```python
xonsh
$PYTHONHUNTER='depth_lt=10,stdlib=False' $XONSH_DEBUG=1 xonsh -c 'echo 1'
```
And this is work perfect! Amazing! Thanks!

But after reading about profiling I don't understand where I should place `ProfileAction` and how I should put it to `$PYTHONHUNTER`?

**Comment by anki-code** [comment]
I'm leaving here the link to my small solution - https://github.com/anki-code/xunter

**Comment by ionelmc** [comment]
Nice. Looks like I have to make a "projects using hunter" section somewhere in the docs.

**Comment by ionelmc** [comment]
Added.

**Comment by anki-code** [comment]
@ionelmc thanks! You a bit forget about rst :) I've fixed in https://github.com/ionelmc/python-hunter/pull/95
